gb.api:
  endpoint:
    manufacturer-url: 'http://${gb.api.endpoint.base-uri}/api/v1/manufacturer'
    category-url: 'http://${gb.api.endpoint.base-uri}/api/v1/category'
    product-url: 'http://${gb.api.endpoint.base-uri}/api/v1/product'
  connection:
    connectTimeout: 60 # Seconds
    readTimeout: 10 # Seconds
    period: 3000 # Millis
    maxPeriod: 5000 # Millis
    maxAttempts: 3
spring.datasource:
  url: "jdbc:postgresql://localhost:5432/gb_shop"
  username: '{cipher}AQBMYkxXMHwi0HfHOEmKCQAwBpFwo1Ga1F3/x/0GlsIs6JaoLF8MOUUeTDLxAnUb11c1MblUfxDvwV6FTjFFs2ohh6o6pCAIJitq5RoZFlPIdEOkL1UrC0D8biYLF1684DVlTRbgFHxjwJ+jdXc0DLO4BuOAWCK7DN2IgwbHejfEDVFotAiocgSi64HfriLpO6UqeaFnwceGUD/LEhe+riowU7ZvCHJ5xn9r8KJZq6jShJSBuSOzUZoF+dnuzJj4q4bIY2trq3+JZZcPoInILXq/+52Gk1MmfewPcm+EaPJ2ZtVrALrMjws0w2Uqvk3UqyXE8fzw0tJ5d43m6iwW64MZgSKjxFq62w9WiYeQcMIeUkBoCTjUW+jn5T6W3heXP+c='
  password: '{cipher}AQBMYkxXMHwi0HfHOEmKCQAwBpFwo1Ga1F3/x/0GlsIs6JaoLF8MOUUeTDLxAnUb11c1MblUfxDvwV6FTjFFs2ohh6o6pCAIJitq5RoZFlPIdEOkL1UrC0D8biYLF1684DVlTRbgFHxjwJ+jdXc0DLO4BuOAWCK7DN2IgwbHejfEDVFotAiocgSi64HfriLpO6UqeaFnwceGUD/LEhe+riowU7ZvCHJ5xn9r8KJZq6jShJSBuSOzUZoF+dnuzJj4q4bIY2trq3+JZZcPoInILXq/+52Gk1MmfewPcm+EaPJ2ZtVrALrMjws0w2Uqvk3UqyXE8fzw0tJ5d43m6iwW64MZgSKjxFq62w9WiYeQcMIeUkBoCTjUW+jn5T6W3heXP+c='
